name = "feedcasket"
main = "src/index.ts"
compatibility_date = "2024-02-08"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "feedcasket-db"
database_id = "f24deb01-02c1-4985-b99e-0bdcd91bcb17"
migrations_dir = "migrations"

# [[r2_buckets]]
# binding = "SCREENSHOTS"
# bucket_name = "feedcasket-screenshots"

[vars]
ENVIRONMENT = "production"

[env.dev]
# Additional configuration for dev if needed
